apiVersion: v1
kind: ReplicationController
metadata:
 name: myweb-rc

spec:
 replicas: 3
 selector:
  env: prod

 template:
  metadata: 
   name: myweb-pod3
   labels: 
    env: prod
  
  spec: 
   containers: 
   - image: httpd
     name: myweb-con



